# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dothtm.psyburr.space
email: dothtm@icloud.com
description: > # this means to ignore newlines until next dict key
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dothtm.psyburr.space" # the base hostname & protocol for your site
twitter_username: dothtm
github_username:  dothtm
mastodon_username:  '@dotHTM@mathstodon.xyz'

# Build settings
markdown: kramdown
md: kramdown

exclude: 
  - node_modules
  - gruntfile.js
  - config.rb
  - brokenLinks.mdown
  - package.json
  - Makefile
  - "*.todo"
  - "*.sublime-*"
  - "*.sh"

logo: /image/dot_logo.png

dateformat: "%b %-d, %Y"
