version: '3'
services:
  jekyll:
    build: 
      context: ./docker/alpine/
      dockerfile: jekyll.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./:/app/static_src/"

  grunt:
    build: 
      context: ./docker/alpine/
      dockerfile: grunt.dockerfile
    ports:
      - "35729:35729"
    volumes:
      - "./:/app/static_src/"

